#created on: Feb 9, 2010
package com.jboss.example

rule "CBU072_Overtime_QualifierRule"
	salience 10000
	when
		$slice: TimeSlice( 
					sliceCreatedByRules  == false, 
					classifiers contains(TimeSliceClassifiers.OUTSIDE_SCHEDULE),
					classifiers contains(TimeSliceClassifiers.WORKED),
					classifiers contains(TimeSliceClassifiers.INVOLUNTARY),
					classifiers contains(TimeSliceClassifiers.OVERTIME_REQUEST),
					classifiers contains(TimeSliceClassifiers.CASH),
					classifiers contains(TimeSliceClassifiers.APPROVED)					
				)				
	then
		System.out.println("OutsideSchedule Compensation");	
		drools.getWorkingMemory().setFocus("OutsideSchedule");
end


/*

1. If the weekly overtime threshold is less than 40,
2. And the value in the weekly overtime threshold plus the duration of the overtime slice
	 puts the value of the weekly overtime threshold to less than or equal to 40,
*/
rule "CBU072_JTP_Overtime_RuleSet"
agenda-group "OutsideSchedule"
	when
		$employee: Employee( $schedule:schedule )
	
		$slice: TimeSlice( 
			employee == $employee,
			$elapsed: elapsed  
			)
		WeeklyAccumulator (
			this == $schedule,
			$OT: weeklyHoursTowardsOT  < 40,
			$FLSA: weeklyHoursTowardsFLSA,		
			eval($elapsed + weeklyHoursTowardsOT  < 40)
			)			
	then

		# 3. Then add the duration of aTimeSlice to WeeklyAccumulator's WeeklyHoursTowardsOTThreshold,
		$OT += $elapsed;

		# 4. And add the duration of aTimeSlice to WeeklyAccumulator's WeeklyHours Towards FLSAThreshold 
		$FLSA +=  $elapsed;

		# 5. And compensate the overtime hours in cash at 1.0x with EC1400
		$slice.addClassifier(TimeSliceClassifiers.EC1400, TimeSliceClassifiers.STRAIGHT);
end


/*
1. If the weekly overtime threshold is less than 40,
2. And the value in the weekly overtime threshold plus the duration of the overtime slice 
puts the value of the weekly overtime threshold to greater than 40,
*/
rule "CBU072_OvertimeCashSplit_Rule"
	when
		$employee: Employee( $schedule:schedule )

		$slice: TimeSlice( 
			employee == $employee,
			$elapsed: elapsed  
			)


		WeeklyAccumulator (
			this == $schedule,
			$OT: weeklyHoursTowardsOT  < 40,
			$FLSA: weeklyHoursTowardsFLSA,		
			eval($elapsed + weeklyHoursTowardsOT  > 40)
			)			
		
		
	then
		
		# 3. Then add the duration of aTimeSlice to WeeklyAccumulator's WeeklyHoursTowardsOTThreshold,
		$OT += $elapsed;
	
		# 4. And add the duration of aTimeSlice to WeeklyAccumulator's WeeklyHours Towards FLSAThreshold,
		$FLSA +=  $elapsed;
	
		# 5. And split the slice at the time when the slice crosses the weekly overtime threshold value of 40,
		int remainder =  40 - $OT;
		int premium = $elapsed - remainder;
		
		TimeSlice overtimeSlice = new TimeSlice();
		overtimeSlice.setElapsed(premium);
		for (TimeSliceClassifiers classifier: $slice.getClassifiers()){
			overtimeSlice.addClassifier(classifier);		
		}

		# 6. And compensate the ovetime hours before the split in cash at 1.0x with EC1400,
		$slice.setElapsed(remainder);

		$slice.addClassifier(TimeSliceClassifiers.OVERTIME_REQUEST, TimeSliceClassifiers.STRAIGHT, TimeSliceClassifiers.EC1400);

		# 7. And compensate the overtime hours after the split in cash at 1.5x with EC1405
		overtimeSlice.addClassifier(TimeSliceClassifiers.OVERTIME_REQUEST, TimeSliceClassifiers.PREMIUM, TimeSliceClassifiers.EC1405);
		overtimeSlice.setSliceCreatedByRules(true);
		$slice.getBusinessDay().addTimeSlice(overtimeSlice);
		
end

/*

1. If the weekly overtime threshold is greater than or equal to 40,
*/
rule "CBU072_OvertimeCashPremium_Rule"
	when
	
		$employee: Employee( $schedule:schedule )

		$slice: TimeSlice( 
			employee == $employee,
			$elapsed: elapsed  
			)


		WeeklyAccumulator (
			this == $schedule,
			$OT: weeklyHoursTowardsOT  >= 40,
			$FLSA: weeklyHoursTowardsFLSA,		
			eval($elapsed + weeklyHoursTowardsOT  > 40)
			)			
	
	
		
	then
		# 2. Then compensate the overtime hours in cash at 1.5x with EC1405,
		$slice.addClassifier(TimeSliceClassifiers.OVERTIME_REQUEST, TimeSliceClassifiers.PREMIUM, TimeSliceClassifiers.EC1405);
		
		# 3. And add the duration of aTimeSlice to WeeklyAccumulator's WeeklyHoursTowardsOTThreshold,
		$OT += $elapsed;

		# 4. And add the duration of aTimeSlice to WeeklyAccumulator's WeeklyHours Towards FLSAThreshold,
		$FLSA +=  $elapsed;

		
end

